# Generated by Django 3.0.4 on 2020-06-14 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_auto_20200524_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('reviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies_app.Reviews')),
            ],
            bases=('movies_app.reviews',),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
    ]
